:global:
  componentName: keycloak-attribute-sync-controller
  githubUrl: https://github.com/appuio/component-keycloak-attribute-sync-controller
  feature_goldenTests: true

docs/antora.yml:
  name: keycloak-attribute-sync-controller
  title: Keycloak Attribute Sync Controller
