= Parameters

The parent key for all of the following parameters is `keycloak_attribute_sync_controller`.

== `namespace`

[horizontal]
type:: string
default:: `syn-keycloak-attribute-sync-controller`

The namespace in which to deploy this component.


== `images`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
controller:
  registry: quay.io
  repository: appuio/keycloak-attribute-sync-controller
  tag: ...
----

Dictionary containing the container images used by this component.


== `resources`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
controller: {}
----
example::
+
[source,yaml]
----
controller:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
----

This dictionary allows overriding the default resource requests.


== `sync_credentials`

[horizontal]
type:: dictionary
default:: `{}`
example::
+
[source,yaml]
----
sync_credentials:
  example-credentials:
    stringData:
      username: sync-user
      password: ...
  example-certificate:
    stringData:
      ca.crt: |
        -----BEGIN CERTIFICATE-----
        ...
----

A key-value map defining multiple `Secret` for referencing in `sync_configurations`.
Each entry will generate a `Secret` with the key as its name.


== `sync_configurations`

[horizontal]
type:: dictionary
default:: `{}`
example::
+
[source,yaml]
----
sync_configurations:
  example:
    url: https://keycloak.example.com/
    loginRealm: master
    username: sync-user
    password: sync-user
    realm: example
    attribute: example.com/special-attribute
    targetAnnotation: example.com/special-attribute
    schedule: "@every 5m"
----

A key-value map defining multiple `AttributeSync`.
Each entry will generate a `AttributeSync` with the key as its name.

Possible parameters are documented https://github.com/appuio/keycloak-attribute-sync-controller#usage[here].
